
export const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const UPDATE_WALLET = 'UPDATE_WALLET';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_CFPASSWORD = 'UPDATE_CFPASSWORD';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_RECENT_TRANSACTIONS_SUCCESS = 'GET_RECENT_TRANSACTIONS_SUCCESS';
export const GET_RECENT_TRANSACTIONS_FAILER = 'GET_RECENT_TRANSACTIONS_FAILER';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILER = 'GET_TRANSACTIONS_FAILER';
export const GET_USER_WALLET_SUCCESS = 'GET_USER_WALLET_SUCCESS';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const UPDATE_TRANSACTIONS_TYPE = 'UPDATE_TRANSACTION_TYPE';
export const ONCHANGE_AMOUNT = 'ONCHANGE_AMOUNT';
export const UPDATE_SELECTED_VALUE = 'UPDATE_SELECTED_VALUE';
export const ONCHANGE_RECIPIENT = 'ONCHANGE_RECIPIENT';
export const ONCHANGE_DESCRIPTION = 'ONCHANGE_DESCRIPTION';
export const SEND_BITCOIN_FAILER = 'SEND_BITCOIN_FAILER';

